// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: crudechain/crudechain/tx.proto

package crudechain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName     = "/crudechain.crudechain.Msg/UpdateParams"
	Msg_CreateCrudeblock_FullMethodName = "/crudechain.crudechain.Msg/CreateCrudeblock"
	Msg_UpdateCrudeblock_FullMethodName = "/crudechain.crudechain.Msg/UpdateCrudeblock"
	Msg_DeleteCrudeblock_FullMethodName = "/crudechain.crudechain.Msg/DeleteCrudeblock"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateCrudeblock(ctx context.Context, in *MsgCreateCrudeblock, opts ...grpc.CallOption) (*MsgCreateCrudeblockResponse, error)
	UpdateCrudeblock(ctx context.Context, in *MsgUpdateCrudeblock, opts ...grpc.CallOption) (*MsgUpdateCrudeblockResponse, error)
	DeleteCrudeblock(ctx context.Context, in *MsgDeleteCrudeblock, opts ...grpc.CallOption) (*MsgDeleteCrudeblockResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCrudeblock(ctx context.Context, in *MsgCreateCrudeblock, opts ...grpc.CallOption) (*MsgCreateCrudeblockResponse, error) {
	out := new(MsgCreateCrudeblockResponse)
	err := c.cc.Invoke(ctx, Msg_CreateCrudeblock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCrudeblock(ctx context.Context, in *MsgUpdateCrudeblock, opts ...grpc.CallOption) (*MsgUpdateCrudeblockResponse, error) {
	out := new(MsgUpdateCrudeblockResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateCrudeblock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteCrudeblock(ctx context.Context, in *MsgDeleteCrudeblock, opts ...grpc.CallOption) (*MsgDeleteCrudeblockResponse, error) {
	out := new(MsgDeleteCrudeblockResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteCrudeblock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateCrudeblock(context.Context, *MsgCreateCrudeblock) (*MsgCreateCrudeblockResponse, error)
	UpdateCrudeblock(context.Context, *MsgUpdateCrudeblock) (*MsgUpdateCrudeblockResponse, error)
	DeleteCrudeblock(context.Context, *MsgDeleteCrudeblock) (*MsgDeleteCrudeblockResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateCrudeblock(context.Context, *MsgCreateCrudeblock) (*MsgCreateCrudeblockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCrudeblock not implemented")
}
func (UnimplementedMsgServer) UpdateCrudeblock(context.Context, *MsgUpdateCrudeblock) (*MsgUpdateCrudeblockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCrudeblock not implemented")
}
func (UnimplementedMsgServer) DeleteCrudeblock(context.Context, *MsgDeleteCrudeblock) (*MsgDeleteCrudeblockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCrudeblock not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCrudeblock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCrudeblock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCrudeblock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateCrudeblock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCrudeblock(ctx, req.(*MsgCreateCrudeblock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCrudeblock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCrudeblock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCrudeblock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateCrudeblock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCrudeblock(ctx, req.(*MsgUpdateCrudeblock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteCrudeblock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteCrudeblock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteCrudeblock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteCrudeblock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteCrudeblock(ctx, req.(*MsgDeleteCrudeblock))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crudechain.crudechain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateCrudeblock",
			Handler:    _Msg_CreateCrudeblock_Handler,
		},
		{
			MethodName: "UpdateCrudeblock",
			Handler:    _Msg_UpdateCrudeblock_Handler,
		},
		{
			MethodName: "DeleteCrudeblock",
			Handler:    _Msg_DeleteCrudeblock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crudechain/crudechain/tx.proto",
}
